### ISSUE TITLE
关于通配符后面的数量描述

### ISSUE THREAD

**Issue by noword** [ifplusor/actrie#1]
比如我想匹配 1234开头，中间任意4个字符，最后是 abcd，只能写成 `1234.{4,4}abcd`吗？
正则中行得通的 `1234....abcd` 或 `1234.{4}` 似乎不能用。

谢谢。

**Comment by ifplusor** [comment]
@noword 是的。
因为需求的不同导致的取舍，这个项目在目标模式的设置上并没有正则那么灵活。

**Comment by noword** [comment]
而且只能匹配一次`.`符号, 我用正则`0123.{4,4}abcd.{4,4}ef01`，也报错了。
现在改用re2的 RE2::Set，但是执行Match后，只能得到match的索引，不能得到位置。

**Comment by ifplusor** [comment]
@noword 我测试`0123.{4,4}abcd.{4,4}ef01`是正常的
![image](https://user-images.githubusercontent.com/9999114/227094942-8806315c-7f18-468e-b769-786b128dc406.png)

**Comment by noword** [comment]
我知道了，是我批量生成的正则在末尾用了.{n,n}。
谢谢。
